function init ()

end

function on_key_up ()
	wl_select_menu_entity ("CMC")
end

function on_key_down ()
   wl_select_menu_entity ("CNC")
end

function on_key_left ()
	wl_select_menu_entity ("STC")
end

function on_key_right ()
	wl_select_menu_entity ("JMP")
end

function on_key_a ()
   wl_mnemonic_set_base (0xB8)
   wl_create_menu ("register", 176, 24, "frame.png")
   wl_create_entity (2, 176, 24, "b", "script/assembler/RS/B.lua", "white", "red", "yellow", "gray")
   wl_create_entity (2, 176, 32, "c", "script/assembler/RS/C.lua", "white", "red", "yellow", "gray")
   wl_create_entity (2, 176, 40, "d", "script/assembler/RS/D.lua", "white", "red", "yellow", "gray")
   wl_create_entity (2, 176, 48, "e", "script/assembler/RS/E.lua", "white", "red", "yellow", "gray")
   wl_create_entity (2, 176, 56, "h", "script/assembler/RS/H.lua", "white", "red", "yellow", "gray")
   wl_create_entity (2, 176, 64, "l", "script/assembler/RS/L.lua", "white", "red", "yellow", "gray")
   wl_create_entity (2, 176, 72, "m", "script/assembler/RS/m.lua", "white", "red", "yellow", "gray")
   wl_create_entity (2, 176, 80, "A", "script/assembler/RS/A.lua", "white", "red", "yellow", "gray")
   wl_append_menu ()
   wl_rundown_task ()
   wl_select_menu_entity ("b")
end

function on_key_x ()

end

function on_key_y ()
   wl_create_textbox (
      "white", 
      "COMPARE WITH ACCUMULATOR      " ..
      "                              " ..
      "CMP compares the numeric value" ..
      "of a register or an address in" ..
      "memory (m) with the contents  " ..
      "of the accumulator and        " ..
      "Indicates the result by set-  " ..
      "ting the carry and zero flags." ..
      "The values being compared will" ..
      "remain unchanged. The flag for" ..
      "zero indicates equality and no" ..
      "carry indicates that the accu-" ..
      "mulator is greater than the   " ..
      "specified byte otherwise that " ..
      "the accumulator is less than  " ..
      "the byte. However, the meaning" ..
      "of the carry flag is reversed " ..
      "when the values have different" ..
      "signs or one of the values is " ..
      "complemented.                 " ..
      "The program tests the         " ..
      "condition flags using one of  " ..
      "the conditional Jump, Call, or" ..
      "Return instructions. For      " ..
      "example, JZ (Jump if Zero)    " ..
      "tests for equality",
      "frame.png"
   )
   wl_create_textbox (
      "white", 
      "FUNCTIONAL DESCRIPTION        " ..
      "                              " ..
      "Comparisons are performed by  " ..
      "subtracting the specified byte" ..
      "from the contents of the accu-" ..
      "mulator, which is why the zero" ..
      "and carry flags which indicate" ..
      "the result. This subtraction  " ..
      "uses the processor's internal " ..
      "registers so that source data " ..
      "is preserved. Because sub-    " ..
      "traction uses two's complement" ..
      "addition, the CMP instruction " ..
      "recomplements the carry flag  " ..
      "generated by the subtraction.",
      "frame.png"
   ) 
end

function on_key_start ()

end

function on_key_back ()

end

init ()
